# Generated by Django 2.2.6 on 2021-08-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BlogUser',
        ),
    ]
